name: Code Styles

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
    types: [closed]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  code-styles:
    name: PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        php-versions: [ '8.0' ]
        operating-system: [ ubuntu-20.04 ]

    steps:
      - name: Setup PHP
        # Commit hash for v2.9.0: https://github.com/shivammathur/setup-php/releases/tag/2.9.0
        uses: shivammathur/setup-php@50980172517227701a2db688415a86573987b6df
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: xdebug

      - name: Checkout session
        uses: actions/checkout@v2

      - name: Setup PHPCS
        run: |
          composer install
          ./vendor/bin/phpcs --config-set ignore_warnings_on_exit 1
          ./vendor/bin/phpcs --config-set ignore_errors_on_exit 1
          ./vendor/bin/phpcs --config-set show_progress 1
          ./vendor/bin/phpcs --config-set colors 1

      - name: PHP Compatibility
        run: |
          ./vendor/bin/phpcs --standard=PHPCompatibility -p --runtime-set testVersion  7.1- src/*

      - name: WordPress Code Standards
        run: |
          ./vendor/bin/phpcs src/* --report=summary --standard=PSR2
          ./vendor/bin/phpcs src/* --report=summary --standard=PSR12
