name: PHPUnit Tests (8.x)

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
    types: [closed]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  test-php:
    name: PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        php-versions: [ '8.1', '8.0' ]
        operating-system: [ ubuntu-20.04 ]

    steps:
      - name: Setup PHP
        # Commit hash for v2.17.0: https://github.com/shivammathur/setup-php/releases/tag/2.17.0
        uses: shivammathur/setup-php@7854a0cae7fa7a5f3feac66d27bae2dc42d1067a
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: xdebug

      - name: Log Debug Information
        run: |
          echo "$GITHUB_REF"
          echo "$GITHUB_EVENT_NAME"
          php --version

      - name: Checkout session
        uses: actions/checkout@v2

      - name: Install PHPUnit
        run: |
          composer require phpunit/phpunit:^9 --update-with-dependencies

      - name: Run PHPUnit Tests
        run: |
          cd _tests
          ../vendor/bin/phpunit
